# Data bn tanishuv 


In [25]:
import pandas as pd 
df=pd.read_csv('cs2_all_tiers_games.csv')

In [26]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 19031 entries, 0 to 19030
Data columns (total 99 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   Unnamed: 0             19031 non-null  int64  
 1   match_id               19031 non-null  int64  
 2   game_id                14542 non-null  float64
 3   tournament             19031 non-null  str    
 4   team1_id               19031 non-null  int64  
 5   team1                  19030 non-null  str    
 6   team2_id               19031 non-null  int64  
 7   team2                  19030 non-null  str    
 8   score1_match           19030 non-null  float64
 9   score2_match           19030 non-null  float64
 10  is_total               19031 non-null  bool   
 11  bestOf                 18896 non-null  float64
 12  score1_game            12368 non-null  float64
 13  score2_game            12368 non-null  float64
 14  map_id                 12321 non-null  float64
 15  map_name     

In [27]:
df.drop([
    'score1_match',
    'score2_match',
    'score1_game',
    'score2_game',
    'Unnamed: 0'
], axis=1, inplace=True)

In [28]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 19031 entries, 0 to 19030
Data columns (total 94 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   match_id               19031 non-null  int64  
 1   game_id                14542 non-null  float64
 2   tournament             19031 non-null  str    
 3   team1_id               19031 non-null  int64  
 4   team1                  19030 non-null  str    
 5   team2_id               19031 non-null  int64  
 6   team2                  19030 non-null  str    
 7   is_total               19031 non-null  bool   
 8   bestOf                 18896 non-null  float64
 9   map_id                 12321 non-null  float64
 10  map_name               12321 non-null  str    
 11  datetime               19031 non-null  str    
 12  team1_win              19031 non-null  int64  
 13  games_played           19030 non-null  float64
 14  team1_player1_id       18281 non-null  float64
 15  team1_player2

In [29]:
df.isnull().sum()

match_id                    0
game_id                  4489
tournament                  0
team1_id                    0
team1                       1
                         ... 
team2_player5_deaths     5508
team2_player5_assists    5508
team2_player5_adr        5508
team2_player5_kast       5508
team2_player5_kddiff     5508
Length: 94, dtype: int64

# encoding

In [30]:
from sklearn.preprocessing import LabelEncoder 
encoder=LabelEncoder()

In [31]:
def encodla(df):
    for col in df.columns:
        if df[col].dtype=='str':
            if df[col].nunique()<5:
                dummies=pd.get_dummies(df[col],prefix=col,dtype=int)
                df=pd.concat([df.drop(columns=[col]),dummies],axis=1)
            else:
                df[col]=encoder.fit_transform(df[col])
    return df

In [32]:
df=encodla(df)

In [33]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 19031 entries, 0 to 19030
Data columns (total 94 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   match_id               19031 non-null  int64  
 1   game_id                14542 non-null  float64
 2   tournament             19031 non-null  int64  
 3   team1_id               19031 non-null  int64  
 4   team1                  19031 non-null  int64  
 5   team2_id               19031 non-null  int64  
 6   team2                  19031 non-null  int64  
 7   is_total               19031 non-null  bool   
 8   bestOf                 18896 non-null  float64
 9   map_id                 12321 non-null  float64
 10  map_name               19031 non-null  int64  
 11  datetime               19031 non-null  int64  
 12  team1_win              19031 non-null  int64  
 13  games_played           19030 non-null  float64
 14  team1_player1_id       18281 non-null  float64
 15  team1_player2

In [34]:
df.isnull().sum()

match_id                    0
game_id                  4489
tournament                  0
team1_id                    0
team1                       0
                         ... 
team2_player5_deaths     5508
team2_player5_assists    5508
team2_player5_adr        5508
team2_player5_kast       5508
team2_player5_kddiff     5508
Length: 94, dtype: int64

In [35]:
num_cols = df.select_dtypes(include=['int64', 'float64']).columns
df[num_cols] = df[num_cols].fillna(df[num_cols].median())

In [36]:
df.isnull().sum()

match_id                 0
game_id                  0
tournament               0
team1_id                 0
team1                    0
                        ..
team2_player5_deaths     0
team2_player5_assists    0
team2_player5_adr        0
team2_player5_kast       0
team2_player5_kddiff     0
Length: 94, dtype: int64

In [43]:
X = df.drop(['team1_win'], axis=1)

In [44]:
y = df['team1_win']

# Scaling

In [45]:
from sklearn.preprocessing import MinMaxScaler

In [46]:
def scaling_qil(df):
    scaler=MinMaxScaler()
    num_col = df.select_dtypes(include=['int64','float64']).columns
    df[num_col]=scaler.fit_transform(df[num_col]) 
    return df

In [47]:
df=scaling_qil(df)

In [48]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 19031 entries, 0 to 19030
Data columns (total 94 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   match_id               19031 non-null  float64
 1   game_id                19031 non-null  float64
 2   tournament             19031 non-null  float64
 3   team1_id               19031 non-null  float64
 4   team1                  19031 non-null  float64
 5   team2_id               19031 non-null  float64
 6   team2                  19031 non-null  float64
 7   is_total               19031 non-null  bool   
 8   bestOf                 19031 non-null  float64
 9   map_id                 19031 non-null  float64
 10  map_name               19031 non-null  float64
 11  datetime               19031 non-null  float64
 12  team1_win              19031 non-null  float64
 13  games_played           19031 non-null  float64
 14  team1_player1_id       19031 non-null  float64
 15  team1_player2

In [49]:
df.sample(8)

,match_id,game_id,tournament,team1_id,team1,team2_id,team2,is_total,bestOf,map_id,...,team2_player4_assists,team2_player4_adr,team2_player4_kast,team2_player4_kddiff,team2_player5_kills,team2_player5_deaths,team2_player5_assists,team2_player5_adr,team2_player5_kast,team2_player5_kddiff
14885,0.118903,0.107918,0.962382,0.397586,0.346026,0.397586,0.694203,True,0.5,1.000000,...,0.097561,0.218499,0.442080,0.133333,0.092784,0.333333,0.027027,0.140675,0.20625,0.147059
12086,0.313743,0.096612,0.391850,0.754818,0.331126,0.754818,0.282609,True,0.5,0.090909,...,0.243902,0.414209,0.723404,0.400000,0.247423,0.357143,0.432432,0.325907,0.68250,0.338235
9358,0.997439,0.886415,0.736677,0.088157,0.299669,0.088157,0.768116,True,0.5,0.272727,...,0.121951,0.372654,0.661939,0.400000,0.154639,0.178571,0.135135,0.339911,0.64250,0.411765
5759,0.118806,0.892096,0.429467,0.396883,0.403974,0.396883,0.414493,False,0.5,1.000000,...,0.146341,0.306971,0.718676,0.386667,0.123711,0.119048,0.162162,0.345640,0.70250,0.455882
1288,0.528266,0.906688,0.075235,0.855800,0.738411,0.855800,0.705797,False,0.5,0.181818,...,0.146341,0.424933,0.626478,0.373333,0.144330,0.130952,0.108108,0.433482,0.73625,0.470588
15701,0.998074,0.886415,0.695925,0.342106,0.591060,0.342106,0.627536,True,0.0,0.272727,...,0.121951,0.372654,0.661939,0.400000,0.154639,0.178571,0.135135,0.339911,0.64250,0.411765
10027,0.019406,0.121046,0.335423,0.033977,0.619205,0.033977,0.046377,True,0.5,0.272727,...,0.121951,0.372654,0.661939,0.400000,0.154639,0.178571,0.135135,0.339911,0.64250,0.411765
4256,0.176205,0.897549,0.435737,0.576606,0.408940,0.576606,0.466667,False,0.5,0.954545,...,0.121951,0.453083,0.527187,0.373333,0.154639,0.178571,0.135135,0.425843,0.68750,0.426471


# Train

In [51]:
X=df.drop('team1_win',axis=1)

In [52]:
y=df['team1_win']

In [53]:
y

0        0.0
1        0.0
2        1.0
3        0.0
4        1.0
        ... 
19026    0.0
19027    0.0
19028    0.0
19029    0.0
19030    0.0
Name: team1_win, Length: 19031, dtype: float64

# train 

In [54]:
from sklearn.model_selection import train_test_split

In [55]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

# Model s

In [56]:
from sklearn.linear_model import LinearRegression 

In [57]:
lr=LinearRegression()

In [58]:
lr.fit(X_train, y_train) 

,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"copy_X copy_X: bool, default=TrueIf True, X will be copied; else, it may be overwritten.",True
,"tol tol: float, default=1e-6The precision of the solution (`coef_`) is determined by `tol` whichspecifies a different convergence criterion for the `lsqr` solver.`tol` is set as `atol` and `btol` of :func:`scipy.sparse.linalg.lsqr` whenfitting on sparse training data. This parameter has no effect when fittingon dense data... versionadded:: 1.7",1e-06
,"n_jobs n_jobs: int, default=NoneThe number of jobs to use for the computation. This will only providespeedup in case of sufficiently large problems, that is if firstly`n_targets > 1` and secondly `X` is sparse or if `positive` is setto `True`. ``None`` means 1 unless in a:obj:`joblib.parallel_backend` context. ``-1`` means using allprocessors. See :term:`Glossary ` for more details.",None
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive. Thisoption is only supported for dense arrays.For a comparison between a linear regression model with positive constraintson the regression coefficients and a linear regression without such constraints,see :ref:`sphx_glr_auto_examples_linear_model_plot_nnls.py`... versionadded:: 0.24",False


# Prediction

In [59]:
y_pred=lr.predict(X_test)
y_pred

array([ 0.4045052 ,  0.55712967,  0.16710969, ...,  0.01985746,
       -0.20195466,  0.88606935], shape=(3807,))

# Evaluation

In [60]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [61]:
r2=r2_score(y_test,y_pred)
mse=mean_squared_error(y_test,y_pred)
rmse=pow(mse,(1/2))
mae=mean_absolute_error(y_test,y_pred)

In [62]:
print(r2)
print(mse)
print(rmse)
print(mae)

0.6065747159752172
0.0815646480418425
0.28559525213462933
0.2100074379253191


# Decision

In [63]:
from sklearn.tree import DecisionTreeRegressor

In [64]:
dr=DecisionTreeRegressor()

In [65]:
dr.fit(X_train,y_train)

,"criterion criterion: {""squared_error"", ""friedman_mse"", ""absolute_error"", ""poisson""}, default=""squared_error""The function to measure the quality of a split. Supported criteriaare ""squared_error"" for the mean squared error, which is equal tovariance reduction as feature selection criterion and minimizes the L2loss using the mean of each terminal node, ""friedman_mse"", which usesmean squared error with Friedman's improvement score for potentialsplits, ""absolute_error"" for the mean absolute error, which minimizesthe L1 loss using the median of each terminal node, and ""poisson"" whichuses reduction in the half mean Poisson deviance to find splits... versionadded:: 0.18 Mean Absolute Error (MAE) criterion... versionadded:: 0.24 Poisson deviance criterion.",'squared_error'
,"splitter splitter: {""best"", ""random""}, default=""best""The strategy used to choose the split at each node. Supportedstrategies are ""best"" to choose the best split and ""random"" to choosethe best random split.",'best'
,"max_depth max_depth: int, default=NoneThe maximum depth of the tree. If None, then nodes are expanded untilall leaves are pure or until all leaves contain less thanmin_samples_split samples.For an example of how ``max_depth`` influences the model, see:ref:`sphx_glr_auto_examples_tree_plot_tree_regression.py`.",None
,"min_samples_split min_samples_split: int or float, default=2The minimum number of samples required to split an internal node:- If int, then consider `min_samples_split` as the minimum number.- If float, then `min_samples_split` is a fraction and `ceil(min_samples_split * n_samples)` are the minimum number of samples for each split... versionchanged:: 0.18 Added float values for fractions.",2
,"min_samples_leaf min_samples_leaf: int or float, default=1The minimum number of samples required to be at a leaf node.A split point at any depth will only be considered if it leaves atleast ``min_samples_leaf`` training samples in each of the left andright branches. This may have the effect of smoothing the model,especially in regression.- If int, then consider `min_samples_leaf` as the minimum number.- If float, then `min_samples_leaf` is a fraction and `ceil(min_samples_leaf * n_samples)` are the minimum number of samples for each node... versionchanged:: 0.18 Added float values for fractions.",1
,"min_weight_fraction_leaf min_weight_fraction_leaf: float, default=0.0The minimum weighted fraction of the sum total of weights (of allthe input samples) required to be at a leaf node. Samples haveequal weight when sample_weight is not provided.",0.0
,"max_features max_features: int, float or {""sqrt"", ""log2""}, default=NoneThe number of features to consider when looking for the best split:- If int, then consider `max_features` features at each split.- If float, then `max_features` is a fraction and `max(1, int(max_features * n_features_in_))` features are considered at each split.- If ""sqrt"", then `max_features=sqrt(n_features)`.- If ""log2"", then `max_features=log2(n_features)`.- If None, then `max_features=n_features`.Note: the search for a split does not stop until at least onevalid partition of the node samples is found, even if it requires toeffectively inspect more than ``max_features`` features.",None
,"random_state random_state: int, RandomState instance or None, default=NoneControls the randomness of the estimator. The features are alwaysrandomly permuted at each split, even if ``splitter`` is set to``""best""``. When ``max_features < n_features``, the algorithm willselect ``max_features`` at random at each split before finding the bestsplit among them. But the best found split may vary across differentruns, even if ``max_features=n_features``. That is the case, if theimprovement of the criterion is identical for several splits and onesplit has to be selected at random. To obtain a deterministic behaviourduring fitting, ``random_state`` has to be fixed to an integer.See :term:`Glossary ` for details.",None
,"max

In [66]:
y_pred=dr.predict(X_test)

In [67]:
y_pred

array([0., 1., 0., ..., 0., 0., 1.], shape=(3807,))

In [68]:
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error

In [69]:
r2=r2_score(y_test,y_pred)
mae=mean_absolute_error(y_test,y_pred)
mse=mean_squared_error(y_test,y_pred)

In [70]:
print('r2:',r2)
print('mae:',mae)
print('mse:',mse)

r2: 0.5527481670566075
mae: 0.09272392960336223
mse: 0.09272392960336223


# k_Fold cross validation

In [71]:
from sklearn.model_selection import  KFold, cross_val_score

In [72]:
from sklearn.model_selection import  KFold, cross_val_score

In [73]:
kf=KFold(n_splits=5,shuffle=True,random_state=42)

In [74]:
kf

KFold(n_splits=5, random_state=42, shuffle=True)

In [76]:
scores=cross_val_score(lr,X,y,cv=kf,scoring='r2')

In [77]:
print(scores)

[0.60657472 0.59001291 0.57492647 0.5806034  0.58306333]


In [78]:
for i in scores:
    print(i)

0.6065747159752173
0.5900129081525536
0.5749264663810935
0.5806034008377774
0.5830633326493072


In [79]:
import numpy as np

In [80]:
np.mean(scores)

np.float64(0.5870361647991897)

In [81]:
np.std(scores)

np.float64(0.010903436396858307)

In [82]:
from sklearn.metrics import make_scorer

In [83]:
mae=make_scorer(mean_absolute_error,greater_is_better=False)

In [85]:
scores=cross_val_score(lr,X,y,cv=kf,scoring=mae)

In [86]:
print(-scores)

[0.21000744 0.20870839 0.21267063 0.211794   0.20950749]


In [87]:
print(-scores.mean())

0.21053759025018967
